### ISSUE TITLE
Create a Logo

### ISSUE THREAD

**Issue by JakobMiksch** [augustinh22/maptime-salzburg#5]
* [x] finish logo
* [x] vector file if possible

**Comment by augustinh22** [comment]
PS made first drafts and is checking on use of Salzburg skyline with the tourism office...

**Comment by augustinh22** [comment]
We have permission to use the skyline. The draft(s) of the logo will be discussed at the next internal meeting.

**Comment by augustinh22** [comment]
We just need a vector file version...

**Comment by JakobMiksch** [comment]
done :tada:
