### ISSUE TITLE
Merge this repo with maptime.io/salzburg website ?

### ISSUE THREAD

**Issue by JakobMiksch** [augustinh22/maptime-salzburg#9]
We have to decide if we need two separate repositories (this + [the other](https://github.com/maptime/salzburg/)), or if we should rather merge them. This would make everything more understandable and maintainable ...

**Comment by augustinh22** [comment]
I agree. I also think, however, that it makes most sense to maintain "internal" organizing minutes/meetings separate from open-source reference materials (e.g. tutorials, slides, workshop docs) -- these could still be in the same repo, but if we ever want to enforce differeing permissions for resources and organising, two repos might be better.

**Comment by njanakiev** [comment]
I think it would be best to keep the documentation and organisational things here and keep the website/posts/slides on the maptime repository. Another option would be maybe a branch on the maptime repository? How would it work with the permissions on the maptime repository?

**Comment by JakobMiksch** [comment]
okay, we just keep the repos separated
